apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-client
  namespace: default
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: deployment-client
  namespace: default
roleRef:
  kind: ClusterRole
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: deployment-client-secret
  annotations:
    kubernetes.io/service-account.name: deployment-client
type: kubernetes.io/service-account-token