apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysql
  ports:
  - port: 3306
    targetPort: 3306

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c291cmFiaA==
  MYSQL_USER: c291cmFiaA==
  MYSQL_PASSWORD: c291cmFiaA==
stringData:
  MYSQL_DATABASE: wordpress

---

apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
      requests:
        memory: "400Mi"
        cpu: "400m"
    ports:
      - containerPort: 3306
    envFrom:
      - secretRef:
          name: mysql-secret
    imagePullPolicy: IfNotPresent