apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - port: 6379
    targetPort: 6379

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    resources:
      limits:
        memory: "200Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
    imagePullPolicy: IfNotPresent

