apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: wordpress
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

---

apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  WORDPRESS_DB_USER: c291cmFiaA==
  WORDPRESS_DB_PASSWORD: c291cmFiaA==
  WORDPRESS_DB_NAME: d29yZHByZXNz
stringData:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_REDIS_NAME: redis-service
  WORDPRESS_REDIS_PORT: "6379"


---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: wordpress
spec:
  containers:
  - name: wordpress
    image: sourabh4584/wordpress:v1
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: wordpress-secret
    imagePullPolicy: IfNotPresent
        