apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  wp-config.php: |
    <?php
    define('WP_REDIS_HOST', 'wordpress-redis');
    define('WP_REDIS_PORT', '6379');

    if (!function_exists('getenv_docker')) {

      function getenv_docker($env, $default) {
        if ($fileEnv = getenv($env . '_FILE')) {
          return rtrim(file_get_contents($fileEnv), "\r\n");
        }
        else if (($val = getenv($env)) !== false) {
          return $val;
        }
        else {
          return $default;
        }
      }
    }

    define( 'DB_NAME', getenv_docker('WORDPRESS_DB_NAME', 'wordpress') );

    define( 'DB_USER', getenv_docker('WORDPRESS_DB_USER', 'example username') );

    define( 'DB_PASSWORD', getenv_docker('WORDPRESS_DB_PASSWORD', 'example password') );

    define( 'WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_NAME', 'redis') );

    define( 'WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', '6379') );


    define( 'DB_HOST', getenv_docker('WORDPRESS_DB_HOST', 'mysql') );

    define( 'DB_CHARSET', getenv_docker('WORDPRESS_DB_CHARSET', 'utf8') );

    define( 'DB_COLLATE', getenv_docker('WORDPRESS_DB_COLLATE', '') );

    define( 'AUTH_KEY',         getenv_docker('WORDPRESS_AUTH_KEY',         'put your unique phrase here') );
    define( 'SECURE_AUTH_KEY',  getenv_docker('WORDPRESS_SECURE_AUTH_KEY',  'put your unique phrase here') );
    define( 'LOGGED_IN_KEY',    getenv_docker('WORDPRESS_LOGGED_IN_KEY',    'put your unique phrase here') );
    define( 'NONCE_KEY',        getenv_docker('WORDPRESS_NONCE_KEY',        'put your unique phrase here') );
    define( 'AUTH_SALT',        getenv_docker('WORDPRESS_AUTH_SALT',        'put your unique phrase here') );
    define( 'SECURE_AUTH_SALT', getenv_docker('WORDPRESS_SECURE_AUTH_SALT', 'put your unique phrase here') );
    define( 'LOGGED_IN_SALT',   getenv_docker('WORDPRESS_LOGGED_IN_SALT',   'put your unique phrase here') );
    define( 'NONCE_SALT',       getenv_docker('WORDPRESS_NONCE_SALT',       'put your unique phrase here') );

    $table_prefix = getenv_docker('WORDPRESS_TABLE_PREFIX', 'wp_');

    define( 'WP_DEBUG', !!getenv_docker('WORDPRESS_DEBUG', '') );


    if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
      $_SERVER['HTTPS'] = 'on';
    }


    if ($configExtra = getenv_docker('WORDPRESS_CONFIG_EXTRA', '')) {
      eval($configExtra);
    }

    if ( ! defined( 'ABSPATH' ) ) {
      define( 'ABSPATH', __DIR__ . '/' );
    }

    require_once ABSPATH . 'wp-settings.php';