apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis-replica
spec:
  selector:
    matchLabels:
      app: redis
      role: replica
      tier: backend
  replicas: {{ .Values.redis.replica.count }}
  template:
    metadata:
      labels:
        app: redis
        role: replica
        tier: backend
    spec:
      containers:
        - name: replica
          image: {{ .Values.redis.replica.image }}
          resources:
          {{- toYaml .Values.redis.replica.resources | nindent 12 }}
          env:
          {{- toYaml .Values.redis.replica.env | nindent 10 }}
          ports:
            - containerPort: 6379
---

