apiVersion: v1
kind: Service
metadata:
  name: wordpress-redis
  labels:
    app: wordpress
spec:
  ports:
    - port: 6379
  selector:
    app: wordpress
    tier: redis
  clusterIP: None

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: wordpress
    tier: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
    imagePullPolicy: IfNotPresent

