apiVersion: v1
kind: Service
metadata:
  name: wordpress-redis
  labels:
    app: {{ .Values.labels.app }}
spec:
  ports:
    - port: {{ .Values.port }}
  selector:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}
  clusterIP: None

---

apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.labels.tier }}
  labels:
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}
spec:
  containers:
  - name: redis
    image: redis:latest
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    ports:
      - containerPort: {{ .Values.port }}
    imagePullPolicy: IfNotPresent

